apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: noop-run-
  namespace: gitlab
spec:
  serviceAccountName: tekton-builder
  pipelineRef:
    name: noop-pipeline
  params:
    - name: branch
      value: "master"
  podTemplate:
    nodeSelector:
      workload.ness2u.xyz/gitlab-runner: "true"
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
